config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :manufacturers, :subsidiaries, :car_categories, :car_models
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_category.rb
class CarCategory < ApplicationRecord
    validates :name, presence: { message: 'Nome não pode ficar em branco' }
    validates :daily_rate, presence: { message: 'Diária não pode ficar em branco' }
    validates :car_insurance, presence: { message: 'Seguro não pode ficar em branco' }
    validates :third_party_insurance, presence: { message: 'Seguro contra terceiros
    não pode ficar em branco' }
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :manufacturer
  belongs_to :car_category
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    validates :name, presence: { message: 'Nome não pode ficar em branco' },
    uniqueness: { message: 'Nome já existente' }
end

app/models/subsidiary.rb
class Subsidiary < ApplicationRecord
    validates :name, :cnpj, :address, uniqueness: { message: 'Filial já existente' }
    validates_cnpj_format_of :cnpj, message: 'CNPJ Inválido'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/car_categories_controller.rb
class CarCategoriesController < ApplicationController
    def index
        @car_categories = CarCategory.all
    end

    def show
        @car_category = CarCategory.find(params[:id])
    end

    def new
        @car_category = CarCategory.new
    end

    def edit
        @car_category = CarCategory.find(params[:id])
    end

    def create
        @car_category = CarCategory.new(car_category_params)
        if @car_category.save
            redirect_to @car_category
        else    
            render :new
        end
    end

    def update
        @car_category = CarCategory.find(params[:id])
        @car_category.update(car_category_params)
        redirect_to @car_category
    end

    def destroy
        @car_category = CarCategory.find(params[:id])
        @car_category.destroy!
        flash[:notice] = 'Categoria deletada com sucesso'
        redirect_to root_path
    end

    private

    def car_category_params
        params.require(:car_category).permit(:name, :daily_rate, :car_insurance, :third_party_insurance)
    end
end

app/controllers/car_models_controller.rb
class CarModelsController < ApplicationController
    def index
        @car_models = CarModel.all
    end

    def show
        @car_model = CarModel.find(params[:id])
    end

    def new
        @car_model = CarModel.new
        @car_categories = CarCategory.all
        @manufacturers = Manufacturer.all
    end

    def create
        @car_model = CarModel.new(car_model_params)
        if @car_model.save
            redirect_to @car_model
        else    
            render :new
        end
    end

    def edit
        @car_model = CarModel.find(params[:id])
        @car_categories = CarCategory.all
        @manufacturers = Manufacturer.all
    end

    def update
        @car_model = CarModel.find(params[:id])
        @car_categories = CarCategory.all
        @manufacturers = Manufacturer.all
        @car_model.update(car_model_params)
        redirect_to @car_model
    end

    def car_model_params
        params.require(:car_model).permit(:name, :year, :manufacturer_id, :motorization, :car_category_id, :fuel_type)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index

    end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
    def index
        @manufacturers = Manufacturer.all
    end

    def show
        @manufacturer = Manufacturer.find(params[:id])
    end

    def new
        @manufacturer = Manufacturer.new
    end

    def edit
        @manufacturer = Manufacturer.find(params[:id])
    end

    def create
        @manufacturer = Manufacturer.new(manufacturer_params)
        if @manufacturer.save
            redirect_to @manufacturer
        else    
            render :new
        end
    end

    def update
        @manufacturer = Manufacturer.find(params[:id])
        @manufacturer.update(manufacturer_params)
        redirect_to @manufacturer
    end

    private

    def manufacturer_params
        params.require(:manufacturer).permit(:name)
    end

end

app/controllers/subsidiaries_controller.rb
class SubsidiariesController < ApplicationController
    def index
        @subsidiaries = Subsidiary.all
    end

    def show
        @subsidiary = Subsidiary.find(params[:id])
    end

    def new
        @subsidiary = Subsidiary.new
    end

    def edit
        @subsidiary = Subsidiary.find(params[:id])
    end

    def create
        @subsidiary = Subsidiary.new(subsidiary_params)
        if @subsidiary.save
            redirect_to @subsidiary
        else    
            render :new
        end
    end

    def update
        @subsidiary = Subsidiary.find(params[:id])
        @subsidiary.update(subsidiary_params)
        redirect_to @subsidiary
    end

    def destroy
        @subsidiary = Subsidiary.find(params[:id])
        @subsidiary.destroy!
        flash[:notice] = 'Filial deletada com sucesso'
        redirect_to root_path
    end

    private

    def subsidiary_params
        params.require(:subsidiary).permit(:name, :cnpj, :address)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/car_categories/_form.html.erb
<% if @car_category.errors.any? %>
    <p>Você deve corrigir os seguintes erros para continuar:</p>
    <% @car_category.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    <% end %>
<% end %>

<%= form_for @car_category do |f| %>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
    <%= f.label :daily_rate, 'Diária' %>
    <%= f.text_field :daily_rate %>
    <%= f.label :car_insurance, 'Seguro' %>
    <%= f.text_field :car_insurance %>
    <%= f.label :third_party_insurance, 'Seguro contra terceiros' %>
    <%= f.text_field :third_party_insurance %>
    <%= f.submit 'Enviar' %>
<% end %>

app/views/car_categories/edit.html.erb
<h1>Editar Categoria</h1>

<%= render partial: 'form', locals: { car_category: @car_category } %>

app/views/car_categories/index.html.erb
 <%= link_to 'Registrar nova categoria', new_car_category_path %>

<% if @car_categories.empty? %>
    <p>Nenhuma categoria de carro cadastrada</p>
<% end %>

 <% @car_categories.each do |car_category| %>
    <%= link_to car_category.name, car_category %>
<% end %>

app/views/car_categories/new.html.erb
<h1>Nova Categoria</h1>

<%= render partial: 'form', locals: { car_category: @car_category } %>

app/views/car_categories/show.html.erb
<%= @car_category.name %>
<%= @car_category.daily_rate %>
<%= @car_category.car_insurance %>
<%= @car_category.third_party_insurance %>

<%= link_to 'Editar', edit_car_category_path(@car_category) %>
<%= link_to 'Deletar', @car_category,  method: :delete, data: { confirm: 'Tem certeza?' } %>
<%= link_to 'Voltar', root_path %>

app/views/car_models/_form.html.erb
<% if @car_model.errors.any? %>
    <p>Você deve corrigir os seguintes erros para continuar:</p>
    <% @car_model.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    <% end %>
<% end %>

<%= form_for @car_model do |f| %>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
    <%= f.label :year, 'Ano' %>
    <%= f.text_field :year %>
    <%= f.label :manufacturer_id, 'Fabricante' %>
    <%= f.collection_select :manufacturer_id, @manufacturers, :id, :name %>
    <%= f.label :motorization, 'Cavalos' %>
    <%= f.text_field :motorization %>
    <%= f.label :car_category_id, 'Categoria' %>
    <%= f.collection_select :car_category_id, @car_categories, :id, :name %>
    <%= f.label :fuel_type, 'Combustivel' %>
    <%= f.text_field :fuel_type %>
    <%= f.submit 'Enviar' %>
<% end %>

app/views/car_models/edit.html.erb
<h1>Editar Modelo</h1>

<%= render partial: 'form', locals: { car_model: @car_model } %>

app/views/car_models/index.html.erb
 <%= link_to 'Registrar novo modelo', new_car_model_path %>

<% if @car_models.empty? %>
    <p>Nenhum modelo de carro cadastrado</p>
<% end %>

 <% @car_models.each do |car_model| %>
    <%= link_to car_model.name, car_model %>
<% end %>

app/views/car_models/new.html.erb
<h1>Novo Modelo</h1>

<%= render partial: 'form', locals: { car_model: @car_model } %>

app/views/car_models/show.html.erb
<%= @car_model.name %>
<%= @car_model.year %>
<%= @car_model.manufacturer.name %>
<%= @car_model.motorization %>
<%= @car_model.car_category.name %>
<%= @car_model.fuel_type %>

<%= link_to 'Editar', edit_car_model_path(@car_model) %>
<%= link_to 'Voltar', root_path %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Rental Cars</h1>
<h3>Bem vindo ao sistema de gestão de locação</h3>

<%= link_to 'Fabricantes', manufacturers_path %>
<%= link_to 'Filiais', subsidiaries_path %>
<%= link_to 'Categorias', car_categories_path %>
<%= link_to 'Modelos', car_models_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalCars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/manufacturers/_form.html.erb
<% if @manufacturer.errors.any? %>
    <p>Você deve corrigir os seguintes erros para continuar:</p>
    <% @manufacturer.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    <% end %>
<% end %>

<%= form_for @manufacturer do |f| %>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
    <%= f.submit 'Enviar' %>
<% end %>

app/views/manufacturers/edit.html.erb
<h1>Atualizar Fabricante</h1>

<%= render partial: 'form', locals: { manufacturer: @manufacturer } %>

app/views/manufacturers/index.html.erb
 <%= link_to 'Registrar novo fabricante', new_manufacturer_path %>

<% if @manufacturers.empty? %>
    <p>Nenhuma fabricante cadastrada</p>
<% end %>

 <% @manufacturers.each do |manufacturer| %>
    <%= link_to manufacturer.name, manufacturer %>
<% end %>

app/views/manufacturers/new.html.erb
<h1>Nova Fabricante</h1>

<%= render partial: 'form', locals: { manufacturer: @manufacturer } %>

app/views/manufacturers/show.html.erb
<%= @manufacturer.name %>

<%= link_to 'Editar', edit_manufacturer_path(@manufacturer) %>

<%= link_to 'Voltar', root_path %>

app/views/subsidiaries/_form.html.erb
<% if @subsidiary.errors.any? %>
    <p>Você deve corrigir os seguintes erros para continuar:</p>
    <% @subsidiary.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    <% end %>
<% end %>

<%= form_for @subsidiary do |f| %>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
    <%= f.label :cnpj, 'CNPJ' %>
    <%= f.text_field :cnpj %>
    <%= f.label :address, 'Endereço' %>
    <%= f.text_field :address %>
    <%= f.submit 'Enviar' %>
<% end %>

app/views/subsidiaries/edit.html.erb
<h1>Atualizar Filial</h1>

<%= render partial: 'form', locals: { subsidiary: @subsidiary } %>

app/views/subsidiaries/index.html.erb
 <%= link_to 'Registrar nova filial', new_subsidiary_path %>

<% if @subsidiaries.empty? %>
    <p>Nenhuma filial cadastrada</p>
<% end %>

 <% @subsidiaries.each do |subsidiary| %>
    <%= link_to subsidiary.name, subsidiary %>
<% end %>

app/views/subsidiaries/new.html.erb
<h1>Nova Filial</h1>

<%= render partial: 'form', locals: { subsidiary: @subsidiary } %>

app/views/subsidiaries/show.html.erb
<%= @subsidiary.name %>
<%= @subsidiary.cnpj %>
<%= @subsidiary.address %>

<%= link_to 'Editar', edit_subsidiary_path(@subsidiary) %>
<%= link_to 'Deletar', @subsidiary,  method: :delete, data: { confirm: 'Tem certeza?' } %>
<%= link_to 'Voltar', root_path %>